---
name: Go test and coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: 4afb26e409fe6d3c6caa1d17b6e1f1e267c036c252fb022b981b082d56c8eb5e
      with:
        coverageCommand: go test -coverprofile=c.out
        debug: true

    - name: Race test
      run: go test -race -v ./...
